API_KEY = '6941537416:AAFmTEFIVaQcBxtmEvGQ9M54m-y1z-LBH8Y'
LOGIN = 'Service User'
PASSWORD = '1qaz@WSX'
DIRECTUM_PROTOCOL = 'http'
DIRECTUM_HOST = 'localhost'
LIST_MESSAGE_BEFORE = "\n-"
LIST_MESSAGE_AFTER = ""